In [72]:
import numpy as np
import sympy as sp
from IPython.display import display



sp.init_printing(use_latex='mathjax')



In [73]:
def partition1(max_range, S):
    max_range = np.asarray(max_range, dtype = int)
    a = np.indices(max_range + 1)
    b = a.sum(axis = 0) <= S
    return (a[:,b].T)

poly_basis = partition1(np.array([1,2,3,4]), 2)
print(poly_basis)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 2 0]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 2 0 0]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 1 0 0]]


In [84]:
z = Symbol('z')
dz = Symbol('\dot{z}')
rot = Symbol('\\theta')
drot = Symbol('\dot{\\theta}')
action = Symbol('a')

state = [z, dz, rot, drot]
display(state)

extra_basis = np.array([])


for p in poly_basis:
    curr_basis = (state[0]**p[0]) * (state[1]**p[1]) * (state[2]**p[2]) * (state[3]**p[3]) * action
    extra_basis = np.append(extra_basis, curr_basis)
    
basis = np.hstack((state, extra_basis))



basis_sp = sp.Matrix(basis)
state_sp = sp.Matrix(state)
display(basis_sp)
display(state_sp)

display(basis_sp.jacobian(state_sp))
display(basis_sp.jacobian(sp.Matrix([action])))

[z, \dot{z}, \theta, \dot{\theta}]

⎡          z           ⎤
⎢                      ⎥
⎢       \dot{z}        ⎥
⎢                      ⎥
⎢        \theta        ⎥
⎢                      ⎥
⎢     \dot{\theta}     ⎥
⎢                      ⎥
⎢          a           ⎥
⎢                      ⎥
⎢    \dot{\theta}⋅a    ⎥
⎢                      ⎥
⎢               2      ⎥
⎢   \dot{\theta} ⋅a    ⎥
⎢                      ⎥
⎢       \theta⋅a       ⎥
⎢                      ⎥
⎢\dot{\theta}⋅\theta⋅a ⎥
⎢                      ⎥
⎢            2         ⎥
⎢      \theta ⋅a       ⎥
⎢                      ⎥
⎢      \dot{z}⋅a       ⎥
⎢                      ⎥
⎢\dot{\theta}⋅\dot{z}⋅a⎥
⎢                      ⎥
⎢   \dot{z}⋅\theta⋅a   ⎥
⎢                      ⎥
⎢             2        ⎥
⎢      \dot{z} ⋅a      ⎥
⎢                      ⎥
⎢         a⋅z          ⎥
⎢                      ⎥
⎢   \dot{\theta}⋅a⋅z   ⎥
⎢                      ⎥
⎢      \theta⋅a⋅z      ⎥
⎢                      ⎥
⎣     \dot{z}⋅a⋅z      ⎦

⎡     z      ⎤
⎢            ⎥
⎢  \dot{z}   ⎥
⎢            ⎥
⎢   \theta   ⎥
⎢            ⎥
⎣\dot{\theta}⎦

⎡      1               0               0                0        ⎤
⎢                                                                ⎥
⎢      0               1               0                0        ⎥
⎢                                                                ⎥
⎢      0               0               1                0        ⎥
⎢                                                                ⎥
⎢      0               0               0                1        ⎥
⎢                                                                ⎥
⎢      0               0               0                0        ⎥
⎢                                                                ⎥
⎢      0               0               0                a        ⎥
⎢                                                                ⎥
⎢      0               0               0         2⋅\dot{\theta}⋅a⎥
⎢                                                                ⎥
⎢      0               0               a                0     

⎡         0          ⎤
⎢                    ⎥
⎢         0          ⎥
⎢                    ⎥
⎢         0          ⎥
⎢                    ⎥
⎢         0          ⎥
⎢                    ⎥
⎢         1          ⎥
⎢                    ⎥
⎢    \dot{\theta}    ⎥
⎢                    ⎥
⎢               2    ⎥
⎢   \dot{\theta}     ⎥
⎢                    ⎥
⎢       \theta       ⎥
⎢                    ⎥
⎢\dot{\theta}⋅\theta ⎥
⎢                    ⎥
⎢            2       ⎥
⎢      \theta        ⎥
⎢                    ⎥
⎢      \dot{z}       ⎥
⎢                    ⎥
⎢\dot{\theta}⋅\dot{z}⎥
⎢                    ⎥
⎢   \dot{z}⋅\theta   ⎥
⎢                    ⎥
⎢             2      ⎥
⎢      \dot{z}       ⎥
⎢                    ⎥
⎢         z          ⎥
⎢                    ⎥
⎢   \dot{\theta}⋅z   ⎥
⎢                    ⎥
⎢      \theta⋅z      ⎥
⎢                    ⎥
⎣     \dot{z}⋅z      ⎦